# Generated by Django 5.2.7 on 2025-10-18 07:14

import django.db.models.deletion
import django.utils.timezone
import home.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicWebsiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('featured_news', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('news', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='clients/logos/')),
                ('website', models.URLField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Portfolio Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('project_type', models.CharField(choices=[('construction', 'Construction'), ('industrial', 'Industrial'), ('transportation', 'Transportation'), ('import_export', 'Import & Export')], default='construction', max_length=20)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('planned', 'Planned')], default='completed', max_length=20)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('project_date', models.DateField(default=django.utils.timezone.now)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to=home.models.portfolio_image_path)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_items', to='home.portfoliocategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Portfolio Items',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=home.models.portfolio_image_path)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.portfolioitem')),
            ],
            options={
                'verbose_name_plural': 'Portfolio Images',
                'ordering': ['display_order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_type', models.CharField(choices=[('upload', 'Uploaded Video'), ('youtube', 'YouTube'), ('vimeo', 'Vimeo')], default='upload', max_length=10)),
                ('video_file', models.FileField(blank=True, null=True, upload_to=home.models.portfolio_video_path)),
                ('video_url', models.URLField(blank=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=home.models.portfolio_image_path)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='home.portfolioitem')),
            ],
            options={
                'verbose_name_plural': 'Portfolio Videos',
                'ordering': ['display_order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter (X)'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('snapchat', 'Snapchat'), ('pinterest', 'Pinterest'), ('github', 'GitHub'), ('behance', 'Behance'), ('dribbble', 'Dribbble')], max_length=50)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(blank=True, max_length=50)),
                ('website_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='home.basicwebsiteinfo')),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ['platform'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=150)),
                ('position', models.CharField(blank=True, max_length=150, null=True)),
                ('quote', models.TextField()),
                ('display', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='home.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='portfolioitem',
            index=models.Index(fields=['project_type', 'status'], name='home_portfo_project_ec4b1c_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioitem',
            index=models.Index(fields=['is_featured', 'is_active'], name='home_portfo_is_feat_b91c71_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioitem',
            index=models.Index(fields=['created_at'], name='home_portfo_created_3da717_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sociallink',
            unique_together={('platform', 'website_info')},
        ),
    ]
