# Generated by Django 5.2.7 on 2025-10-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustrialPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='XPENG P7', max_length=200)),
                ('hero_image', models.ImageField(default='industrial/hero/car-bg.jpg', upload_to='industrial/hero/')),
                ('hero_icon_text', models.CharField(default='X', help_text='Text for the hero icon', max_length=10)),
                ('range_value', models.CharField(default='576 km', max_length=50)),
                ('range_label', models.TextField(default='Up to 570 km WLTP<br>Range')),
                ('acceleration_value', models.CharField(default='4.1 s', max_length=50)),
                ('acceleration_label', models.TextField(default='0-100 km/h<br>(AWD)')),
                ('charge_value', models.CharField(default='10-80 %', max_length=50)),
                ('charge_label', models.TextField(default='Charge in 29<br>Minutes*')),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Industrial Page',
                'verbose_name_plural': 'Industrial Page',
            },
        ),
    ]
