# Generated by Django 5.2.7 on 2025-10-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_industrialpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industrialpage',
            name='acceleration_label',
        ),
        migrations.RemoveField(
            model_name='industrialpage',
            name='acceleration_value',
        ),
        migrations.RemoveField(
            model_name='industrialpage',
            name='charge_label',
        ),
        migrations.RemoveField(
            model_name='industrialpage',
            name='charge_value',
        ),
        migrations.RemoveField(
            model_name='industrialpage',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='industrialpage',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='industrialpage',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='industrialpage',
            name='range_label',
        ),
        migrations.RemoveField(
            model_name='industrialpage',
            name='range_value',
        ),
        migrations.AddField(
            model_name='industrialpage',
            name='battery',
            field=models.TextField(default='', help_text='e.g. Up to 570 km WLTP Range'),
        ),
        migrations.AddField(
            model_name='industrialpage',
            name='motor',
            field=models.CharField(default='', help_text='e.g. 576 km', max_length=50),
        ),
        migrations.AddField(
            model_name='industrialpage',
            name='rangee',
            field=models.TextField(default='', help_text='e.g. 0-100 km/h (AWD)'),
        ),
        migrations.AddField(
            model_name='industrialpage',
            name='top_speed',
            field=models.CharField(default='', help_text='e.g. 4.1 s', max_length=50),
        ),
        migrations.AlterField(
            model_name='industrialpage',
            name='hero_title',
            field=models.CharField(default='Product Name', max_length=200),
        ),
    ]
