# Generated by Django 5.2.7 on 2025-10-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_industrialpage_acceleration_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportExportProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of the product category, e.g., Coffee Exports', max_length=100)),
                ('description', models.TextField(help_text='A short paragraph describing the product or service.')),
                ('image', models.ImageField(help_text='Upload an image representing the product category.', upload_to='products/')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to temporarily hide this category from the site.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls display order on the website.')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ['order'],
            },
        ),
    ]
