# Generated by Django 5.2.7 on 2025-10-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_importexportproductcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importexportproductcategory',
            options={'ordering': ['order'], 'verbose_name': 'Import Export', 'verbose_name_plural': 'Import Exports'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='website',
        ),
        migrations.AddField(
            model_name='client',
            name='category',
            field=models.CharField(choices=[('all', 'All'), ('transportation', 'Transportation'), ('construction', 'Construction'), ('import_export', 'Import and Export'), ('industrial', 'Industrial')], default='all', max_length=50),
        ),
    ]
