# Generated by Django 5.2.7 on 2025-11-04 09:29

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_importexportproductcategory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='category',
            field=models.CharField(choices=[('all', 'All'), ('transportation', 'Transportation'), ('construction', 'Construction'), ('import_export', 'Import and Export'), ('industrial', 'Industrial')], db_index=True, default='all', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='importexportproductcategory',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='importexportproductcategory',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='importexportproductcategory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='importexportproductcategory',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='importexportproductcategory',
            name='title',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='industrialpage',
            name='battery',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='industrialpage',
            name='hero_icon_text',
            field=models.CharField(default='X', max_length=10),
        ),
        migrations.AlterField(
            model_name='industrialpage',
            name='hero_title',
            field=models.CharField(db_index=True, default='Product Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='industrialpage',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='industrialpage',
            name='motor',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='industrialpage',
            name='rangee',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='industrialpage',
            name='top_speed',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='portfoliocategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='is_primary',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='project_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='project_type',
            field=models.CharField(choices=[('construction', 'Construction'), ('industrial', 'Industrial'), ('transportation', 'Transportation'), ('import_export', 'Import & Export')], db_index=True, default='construction', max_length=20),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('planned', 'Planned')], db_index=True, default='completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter (X)'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('snapchat', 'Snapchat'), ('pinterest', 'Pinterest'), ('github', 'GitHub'), ('behance', 'Behance'), ('dribbble', 'Dribbble')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='author_name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='display',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['category', 'active'], name='home_client_categor_d123a6_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['active', 'name'], name='home_client_active_feddfc_idx'),
        ),
        migrations.AddIndex(
            model_name='importexportproductcategory',
            index=models.Index(fields=['is_active', 'order'], name='home_import_is_acti_b49967_idx'),
        ),
        migrations.AddIndex(
            model_name='importexportproductcategory',
            index=models.Index(fields=['order', 'is_active'], name='home_import_order_7eefd7_idx'),
        ),
        migrations.AddIndex(
            model_name='industrialpage',
            index=models.Index(fields=['is_active'], name='home_indust_is_acti_1eb374_idx'),
        ),
        migrations.AddIndex(
            model_name='portfoliocategory',
            index=models.Index(fields=['name'], name='home_portfo_name_0f11ed_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioimage',
            index=models.Index(fields=['portfolio_item', 'is_primary'], name='home_portfo_portfol_745c8e_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioimage',
            index=models.Index(fields=['portfolio_item', 'display_order'], name='home_portfo_portfol_eeef5c_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioitem',
            index=models.Index(fields=['project_type', 'is_active', 'is_featured'], name='home_portfo_project_79ac47_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioitem',
            index=models.Index(fields=['project_type', 'is_active', 'created_at'], name='home_portfo_project_321462_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioitem',
            index=models.Index(fields=['is_active', 'is_featured', 'created_at'], name='home_portfo_is_acti_fd7ed5_idx'),
        ),
        migrations.AddIndex(
            model_name='portfoliovideo',
            index=models.Index(fields=['portfolio_item', 'display_order'], name='home_portfo_portfol_6b3b72_idx'),
        ),
        migrations.AddIndex(
            model_name='sociallink',
            index=models.Index(fields=['website_info', 'platform'], name='home_social_website_c855de_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['display', 'created_at'], name='home_testim_display_a1d25a_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['client', 'display'], name='home_testim_client__7f3d7d_idx'),
        ),
    ]
