# Generated by Django 5.2.7 on 2025-11-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_client_active_alter_client_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landing_background_image', models.ImageField(blank=True, null=True, upload_to='hero_images/')),
                ('landing_background_video', models.FileField(blank=True, null=True, upload_to='hero_videos/')),
                ('construction_background_image', models.ImageField(blank=True, null=True, upload_to='hero_images/')),
                ('construction_background_video', models.FileField(blank=True, null=True, upload_to='hero_videos/')),
                ('industrial_background_image', models.ImageField(blank=True, null=True, upload_to='hero_images/')),
                ('industrial_background_video', models.FileField(blank=True, null=True, upload_to='hero_videos/')),
                ('import_export_background_image', models.ImageField(blank=True, null=True, upload_to='hero_images/')),
                ('import_export_background_video', models.FileField(blank=True, null=True, upload_to='hero_videos/')),
                ('transport_background_image', models.ImageField(blank=True, null=True, upload_to='hero_images/')),
                ('transport_background_video', models.FileField(blank=True, null=True, upload_to='hero_videos/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Media',
                'verbose_name_plural': 'Hero Media',
            },
        ),
    ]
